### ISSUE TITLE
Offer PInvoke.ILMerge NuGet package the merge P/Invokes into consuming assembly

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#106]
I expect some folks will more readily consume the work of this project if they can merge the P/Invokes they use into their assembly rather than shipping all the unused ones as well in a separate assembly. 

A NuGet package that uses ILMerge as a build step may allow this process to be very easy for consumers to opt into.

**Comment by jmelosegui** [comment]
This is a really interesting feature I would personally use it if it were available. 
I am wondering how much [ILMerge MSBuild task NuGet package](https://ilmergemsbuild.codeplex.com/) project could help us to solve this issue or if we really need to implement our own version due to some limitation. 
I will try to accomplish the goal of this issue using that package and I''l come back with some feedback.

**Comment by jmelosegui** [comment]
After some tests it doesn't seem to offer a full control over what to merge or in which order (also see this [comment](https://ilmergemsbuild.codeplex.com/discussions/578156) form the author). 

Any way. If we create a nuget package that, base on configuration, it allows us to choose assemblies to merge using ILMerge within MSBuild, that could be useful in more than one scenario. So I don't know if the name "PInvoke.ILMerge" is too specific and this feature deserve its own project.

Thoughts?

**Comment by AArnott** [comment]
Thanks for the investigation, @jmelosegui. It's been a long time since I've used ILMerge. I recall that it can demote merged types' visibility from public to internal, which would be useful. I hope it also can drop unused types and methods.

I suspect that comment you linked to about ILMerge being rather unused lately is probably true. And the complexity of a general purpose project is probably going to be higher than the specific case of merging in libraries from this project. 

So I think the first thing to do is find out how well we can get it to work by hand. And assess whether it's valuable to pursue at all. Then we can go on to see if it's specialized enough in that scenario to warrant a PInvoke specific kind of package.

**Comment by vbfox** [comment]
Personally I don't find the merging so useful but it might interest some authors. Especially library authors that want to provide a small self-contained lib. But I think that using git submodules to reference this repo and including only the needed files would be easier than the complexities of an IL level merge.

Regarding the merge tool https://github.com/gluck/il-repack is an OSS and maintained alternative to ILMerge that could be investigated.

> I hope it also can drop unused types and methods.

As far as I know it's more the domain of the mono linker project than the merge tools. And mono linker isn't really maintained (It evolved into the Xamarin packager for android/iOS but that's not OSS.

**Comment by jmelosegui** [comment]
@AArnott 

> I hope it also can drop unused types and methods.

ILMerge don't offer that feature. Maybe we can evaluate a tool like Mono.Cecil to do some static analysis and strip off the "unused" methods and types after the merge.

Thougths?

**Comment by AArnott** [comment]
Yes, I'm sure we could build it. There would be complications although I expect we could work through them. 
I'm totally cool with not spending time on this till we have would-be customers asking for it.
