### ISSUE TITLE
StyleCop.Analyzers is not propagating to projects referencing Windows.Core

### ISSUE THREAD

**Issue by jmelosegui** [AArnott/pinvoke#114]
I think we need to do something similar to #101 but that is causing a problem with Visual Studio _(at least on my PC)_. 

See [NuGet/Home/#1831](https://github.com/NuGet/Home/issues/1831) for more details.

**Comment by AArnott** [comment]
Oh, so _that's_ why I'm seeing some reference warning icons in Solution Explorer lately. :( Thanks for the insight.

Anyway, ya I think the workaround for this for now is to explicitly add StyleCop.Analyzers to all project.json files. Do you have time to do that?
