### ISSUE TITLE
Code generation should also create byte[] parameter overloads where byte* is observed

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#157]
For example, in the below p/invoke method, we want to generate _both_ an overload that takes `IntPtr` for all native pointer parameters, _and_ another overload where the `byte*` parameter type is treated specially by replacing it with `byte[]`.

It seems useful to generate `byte[]` overloads both with native pointers for the other parameters as well as of course the `IntPtr` variety. Meaning that we generate 3 overloads instead of 1.

So this hand-written method:

``` csharp
public static unsafe extern SECURITY_STATUS NCryptDecrypt(
    SafeKeyHandle hKey,
    byte* pbInput,
    int cbInput,
    void* pPaddingInfo,
    byte* pbOutput,
    int cbOutput,
    out int pcbResult,
    NCryptEncryptFlags dwFlags);
```

Would generate these three overloads: (the first is already generated, the rest are proposed)

``` csharp
public static unsafe extern SECURITY_STATUS NCryptDecrypt(
    SafeKeyHandle hKey,
    IntPtr pbInput,
    int cbInput,
    IntPtr pPaddingInfo,
    IntPtr pbOutput,
    int cbOutput,
    out int pcbResult,
    NCryptEncryptFlags dwFlags);

public static unsafe extern SECURITY_STATUS NCryptDecrypt(
    SafeKeyHandle hKey,
    byte[] pbInput,
    int cbInput,
    IntPtr pPaddingInfo,
    byte[] pbOutput,
    int cbOutput,
    out int pcbResult,
    NCryptEncryptFlags dwFlags);

public static unsafe extern SECURITY_STATUS NCryptDecrypt(
    SafeKeyHandle hKey,
    byte[] pbInput,
    int cbInput,
    void* pPaddingInfo,
    byte[] pbOutput,
    int cbOutput,
    out int pcbResult,
    NCryptEncryptFlags dwFlags);
```

**Comment by jmelosegui** [comment]
Well, in this case why not having only `byte[]`? 
Is there any reason to actually need the `IntPtr` and `byte*` overloads?

I thought we introduced pointers to have more meaningful parameters, and code generation to solve the gap for those languages that cannot call pointer exposing methods, but on those scenarios where we can use an array I don't see the need of the pointer at all (since the parameter is meaningful enough and it can be used by all languages)

**Comment by AArnott** [comment]
@jmelosegui: that's a fair question.
There are two reasons for using `byte*` instead of `byte[]`. These reasons aren't usually compelling enough to warrant using `byte*` so most methods that can should probably use `byte[]`. But for a few methods or libraries, they are quite compelling. They are:
1. `byte*` can point anywhere, including (for example) the middle of a `byte[]`. So if you already have an array with the content you want to pass in, but that content isn't at the start of the array, `byte*` lets you point directly at it, whereas `byte[]` requires that you copy the whole content into a new array just so it's at the beginning of it.
2. `byte*` enables you to be certain that the memory doesn't get copied or moved around by the CLR. `byte[]` as a reference type can be moved during a GC's defragmentation of memory. If your data is sensitive (say, as part of a cryptographic operation) best practices suggest you scrub the buffer when you're done so that memory dumps don't capture the data. But if the buffer gets copied around in memory by the GC, you can't effectively scrub all the old locations. Locking the buffer location mitigates this, and a very convenient way to do this (if it's all local variables within a method) is using C# `fixed` with pointers and not messing with multiple levels of try/finally and GC pinning a `byte[]`.

So I expect to use this enhancement primarily in the BCrypt and NCrypt libraries (where I'm already writing these overloads by hand) and probably nowhere else.

**Comment by vbfox** [comment]
I'm also using pointer inside arrays (Wrapped in an ArraySegment) for IO access to USB devices without allocating memory for each call.

It's not necessary for most API but if the codegen can do them automatically, why not have them ?

**Comment by jmelosegui** [comment]
Thank you @AArnott and @vbfox for pointing out those use cases. Now I get the reasons behind this issue.

**Comment by AArnott** [comment]
I've edited the proposal to include the addition of the `MarshalAsAttribute` in the generated code.

**Comment by AArnott** [comment]
I've removed `[MarshalAs]`, since the generated methods are never P/Invoke methods themselves so it's not applicable.
Also: I've added a 3rd overload for folks who want to pass in `byte[]` and native pointers for other parameters. I discovered the need for this combination during the migration to the code generated second overload -- a lot of my own extra overloads had this combination.

**Comment by jmelosegui** [comment]
> Also: I've added a 3rd overload for folks who want to pass in byte[] and native pointers for other parameters.

That makes a lot sense.
