### ISSUE TITLE
test classes and product classes shouldn't share a filename 

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#163]
Having Bcrypt.cs be the name of the file with the product code as well as the test code is confusing.

**Comment by vbfox** [comment]
+1000 ;-)

**Comment by AArnott** [comment]
so what do we call it? 
Per stylecop rules, the filename and class name should match. But if we change the class name, the test explorer will show tests with something other than "Kernel32.SomeMethod". I really liked that, which is why it is the way it is.
So the question is, what do we change it to? "Kernel32Tests.SomeMethod"?

It's an option to turn off the StyleCop rule, BTW. But I find the test class and product class being exactly the same to also be a bit confusing, and harder to jump to the intended file using Navigate To.

**Comment by jmelosegui** [comment]
Folks using xUnit usually call the class [Something]Facts _(I assume to be consistent with the `[Fact]` attribute)_

**Comment by AArnott** [comment]
Fine by me.
