### ISSUE TITLE
Add a constructor with preexistingHandle and ownsHandle to all SafeHandles

### ISSUE THREAD

**Issue by vbfox** [AArnott/pinvoke#198]
Some of our `SafeHandle` have it but others don't. I think that we should be consistent and always provide this constructor that is really useful when interacting with other code (Like passing handles created by WPF or winforms to PInvoke methods)

``` csharp
/// <summary>
/// Initializes a new instance of the <see cref="SafeThemeHandle"/> class.
/// </summary>
/// <param name="preexistingHandle">An object that represents the pre-existing handle to use.</param>
/// <param name="ownsHandle">
///     <see langword="true" /> to have the native handle released when this safe handle is disposed or finalized;
///     <see langword="false" /> otherwise.
/// </param>
public SafeThemeHandle(IntPtr preexistingHandle, bool ownsHandle = true)
    : base(IntPtr.Zero, ownsHandle)
{
    this.SetHandle(preexistingHandle);
}
```

(The info should also be added to CONTRIBUTING in this case)

See #197 for a PR adding 2 such constructors.

**Comment by AArnott** [comment]
:+1: 
is there more discussion needed?

**Comment by AArnott** [comment]
I guess per the #197 PR, the proposed xml doc comments on the `ownsHandle` parameter may need some work.

**Comment by vbfox** [comment]
Updated the comments as we discussed in PR

**Comment by AArnott** [comment]
@vbfox I think you've taken care of all this. So closing.
