### ISSUE TITLE
HResult is missing a method to get an exception from it

### ISSUE THREAD

**Issue by vbfox** [AArnott/pinvoke#199]
We already have `ThrowOnFailure` calling `Marshal.ThrowExceptionForHR` but don't have any equivalent to `Marshal.GetExceptionForHR`.

``` csharp
Foo Function()
{
    Foo result;
    HResult hr = SomePInvoke(out result);
    if (hr.Succeeded)
    {
        return result;
    }
    else
    {
        if (hr == /*Some value*/)
        {
            throw MyError();
        }
        throw hr.GetException();
    }
}
```

It's often possible to do without but it's sometimes preferable to have explicit `throw` for control-flow and it ease porting code using the `Mashal` class

**Comment by AArnott** [comment]
What's wrong with simply calling `Marshal.GetExceptionForHR(int)` passing in the `HResult`? 
Will fixing this issue unblock someone, or simply make it a bit more convenient by offering it on the class itself?

**Comment by vbfox** [comment]
> What's wrong with simply calling Marshal.GetExceptionForHR(int) passing in the HResult? 

Nothing it's just harder to discover (always the problem with implicit casts)

> Will fixing this issue unblock someone, or simply make it a bit more convenient by offering it on the class itself?

Just for convenience :)
