### ISSUE TITLE
Methods used in SafeHandles 'ReleaseHandle' should have a ReliabilityContract

### ISSUE THREAD

**Issue by vbfox** [AArnott/pinvoke#203]
As pointed in the [`SafeHandle` source code](http://referencesource.microsoft.com/#mscorlib/system/runtime/interopservices/safehandle.cs,110) :

> ```
>   Also, you probably want to define CloseHandle
>   somewhere, and remember to apply a reliability contract to it.
> 
>   [SuppressUnmanagedCodeSecurity]
>   internal static class MyNativeMethods {
>       [DllImport("kernel32")]
>       private static extern MySafeHandleSubclass CreateHandle(int someState);
> 
>       [DllImport("kernel32", SetLastError=true), ReliabilityContract(Consistency.WillNotCorruptState, Cer.Success)]
>       private static extern bool CloseHandle(IntPtr handle);
>   }
> ```

The method also need to be in a class marked with `[SuppressUnmanagedCodeSecurity]` but this change might be made more globally as discussed in #202.

**Comment by AArnott** [comment]
Interesting. I wonder what the reliability contract really signifies and whether we can make such promises for all the close handle methods. And will it work if we _don't_ specify the security attribute (per our decision on #202)?

**Comment by vbfox** [comment]
I think that the security attribute is mandatory to avoid CAS throwing exceptions during the CER execution (At least for the few methods called during ReleaseHandle) so even without #202 we might want the attribute on those few methods.

For what the ReliabilityContract I don't know. My knowledge about CER is really limited :) Might need more investigation before we do anything.

**Comment by AArnott** [comment]
Can we add the security attribute to the method rather than the whole class? I'd feel better about it if so.

**Comment by arlm** [comment]
Would this be a good fit for 2.0 milestone?

**Comment by AArnott** [comment]
No need to wait for 2.0 if it's not a breaking change.
