### ISSUE TITLE
Shims/contracts

### ISSUE THREAD

**Issue by clairernovotny** [AArnott/pinvoke#210]
Should these be using the dll names directly or the shim dlls that redirect the entry points? It seems like a subset these could be useful on UWP development but those need to point to the shim dll's for proper factoring on other devices.

**Comment by AArnott** [comment]
If by shim DLLs you mean the Win32 API Sets, [yes, we do that](https://github.com/AArnott/pinvoke/blob/master/CONTRIBUTING.md#win32-api-sets). Not all functions are defined in Win32 API sets, but those that do we use the proper DLL names for. And all of them are factored for desktop vs. portable appropriately.

If I misunderstand your point, let me know and we can reactivate.

**Comment by clairernovotny** [comment]
:+1: nope, you got it - I just was poking around and must have missed those :)
