### ISSUE TITLE
Display badges for amount of work completed for a native binary

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#24]
We should display badges in HTML rendered versions of our README.md file indicating how many exported functions of each native binary we have P/Invoke methods for. For example, if Kernel32.dll has 533 exported functions and we have p/invoke methods for 12 of them, the badge might look like this:

![P/Invokes](https://img.shields.io/badge/Kernel32-12%2F533-orange.svg)
## Benefits
1. Set expectations appropriately with consumers of the packages as to the likelihood that what they care about is already in there.
2. I think it may help motivate contributors to drive the numbers higher as it will make a visible different on our landing page and make the project more compelling.
## Design

There are two halves to the analysis we need to do: 
1. We need to create a maintainable list of documented, exported methods from a native binary.
2. We need to create a maintainable list of `[DllImport]` methods in the managed P/Invoke library for that native binary.

The process should involve extracting the right set of method names from the native binary and maintaining them in a list. Then assembling a similar list from the managed binary. These lists should be created such that method names will match for each list if they exist in both.
### Native binary analysis

The following command will print out all exported functions (i.e. candidates for P/Invokes)

```
dumpbin /exports LIBNAME.dll
```

Once we have this list, we'll need to de-duplicate for ansi vs. Unicode versions. We should recognize when a method ends with `A` or `W`, and if so, check for another method with the same name except the alternate final letter. When we see this, we report the root method name (without the `A` or `W` suffix). If we don't recognize such a pattern, we report the full method name.

The resulting list should be checked into source control as a text file with exactly one function name per line. Its content should be sorted alphabetically. The filename should be LIBNAME.exports.txt. While we should have a script that can produce this file, as its results would only vary with the version of the native DLL, and as we want a consistent target to aim for across dev and build machines, we should check in the result and only update it when a new version of the native library is released. This also lets us (potentially) hand edit the 'target' file to remove functions that are undocumented and thus not intended to be P/Invoked into.

The build should copy this LIBNAME.exports.txt file as a build output.
### Managed P/Invoke assembly analysis

Use reflection on the managed P/Invoke library to find all static methods (independent of their visibility) that have `[DllImport]` attributes on them. When the `DllImportAttribute.Entrypoint` property is set on the attribute, report that as the native function name. Otherwise report the method name itself.

This list should be generated at build time and saved to a text file named LIBNAME.pinvokes.txt and dropped as a build output. Each line should contain exactly one of the names reported as described above and these lines should be sorted alphabetically.
### Producing shields/badges

The LIBNAME.exports.txt and LIBNAME.pinvokes.txt files should be found side-by-side as build outputs. Perhaps in a dedicated directory such as `bin\debug\exports`. These files should be captured by AppVeyor as artifacts.

A simple build-time script will compare the LIBNAME.exports.txt and LIBNAME.pinvokes.txt file to count how many lines each contains to formulate a string with the form `X/Y` where `X` is the number of lines in the LIBNAME.pinvokes.txt file and `Y` is the number of lines in the LIBNAME.exports.txt file. This string can then be injected into this URL to replace PLACEHOLDER:

`https://img.shields.io/badge/P%2FInvokes-PLACEHOLDER-orange.svg`

We might even change the color based on how `X` and `Y` compare to each other. For example:

| Condition | Color | Example |
| --- | --- | --- |
| X = Y | Green | ![P/Invokes](https://img.shields.io/badge/Kernel32-100/100-green.svg) |
| else X > Y \* 8/10 | YellowGreen | ![P/Invokes](https://img.shields.io/badge/Kernel32-97/100-yellowgreen.svg) |
| else X > Y \* 4/10 | Orange | ![P/Invokes](https://img.shields.io/badge/Kernel32-43/100-orange.svg) |
| else X > 0 | Red | ![P/Invokes](https://img.shields.io/badge/Kernel32-2/100-red.svg) |
| else | LightGrey | ![P/Invokes](https://img.shields.io/badge/Kernel32-5/100-lightgrey.svg) |

These badges should act as hyperlinks to a document with a table that compares the LIBNAME.pinvokes.txt and LIBNAME.exports.txt file so users can quickly discover whether the functions they need are already available. 
## Unsolved
1. Is executing `dumpbin /exports` and parsing the output really the best way to go or is there a programmatic approach we can take instead?
2. Somehow we need to get this X/Y string or URL into an <IMG SRC> such that it appears in renderings of README.md. 
3. We could also produce a Markdown table listing all the exported functions and a column showing whether we have a P/Invoke method for it. But where/how would this Markdown file be hosted/viewed?

**Comment by jmelosegui** [comment]
> But where/how would this Markdown file be hosted/viewed?

Might be as a per library "drill down" link using the library name in the existing PInvoke package table.

**Comment by AArnott** [comment]
Yes, the location of the link seems straightforward. But what would it link _to_? GitHub only shows markdown checked into SCC. But I don't want a file that changes with every commit. I'd rather it be a build output, or published to another server somewhere.

**Comment by AArnott** [comment]
I've added a paragraph explaining that the badges should be hyperlinks to that document, per your recommendation @jmelosegui

**Comment by vbfox** [comment]
The fun part about programatic access to exports is that implementing it would actually help in adding 2 more dlls DbgHelp and Imagehlp: https://stackoverflow.com/questions/4353116/listing-the-exported-functions-of-a-dll

**Comment by AArnott** [comment]
Cool. :)

**Comment by vbfox** [comment]
For the link lets list the options I can think of :
- Hosting a server somewhere with that functionality, either a fork of shields.io or something custom
- Convince appveyor to solve https://github.com/appveyor/ci/issues/403 and generate the pictures as artifact (Potentially just downloading what shields.io generate)
- Push the pictures as a commit to github after each build.
  - Doing it to `gh-pages` is possible but it'll very fast accumulate history
  - Force-pushing is a good solution but having it in the same repo would still generate some noise for contributors
  - Another repository where the build force-push could be a good solution `AArnott/pinvoke-shields`
  - Not sure that github would appreciate us using them as an hosting provider...
- Get shield to add some features (so https://github.com/badges/shields/issues/555 )

**Comment by AArnott** [comment]
I'd say badges/shields#555 is the preferred option. I don't want folks to have to manually push updates anywhere, and I don't think I want the build pushing commits either. I don't think GitHub will mind us using them as a web server for this since with their GitHub.io pages they already are promoting exactly that. But the process of getting changes there would require that we be careful to only do so when building in AppVeyor from the master branch. There may be other concerns as well.

Personally, I think if we have to implement the solution, we should implement badges/shields#555 ourselves and send them a PR. If they don't take the PR, we can talk about hosting that feature on our own server. But I suspect given how diverse they are already that they'd accept the PR. We can give it a couple days to see how they reply to the issue, to see if they'd do it themselves soon or accept a PR.

Thoughts?

**Comment by vbfox** [comment]
Yes https://github.com/badges/shields/issues/555 is the cleanest solution, I wonder what they'll say

**Comment by jmelosegui** [comment]
> Use reflection on the managed P/Invoke library to find all static methods

Which version of the manage P/Invoke Library should be used when exist more than one (Portable or Desktop)?

**Comment by AArnott** [comment]
desktop, since that will always be a superset of portable

**Comment by AArnott** [comment]
I've sent PR #35 that adds ImageHlp and DbgHelp projects

**Comment by AArnott** [comment]
#45 has been merged, which adds the LIBNAME.exports.txt file.
