### ISSUE TITLE
[Missing API]keybd_event, mouse_event

### ISSUE THREAD

**Issue by h82258652** [AArnott/pinvoke#287]
These two api is very useful for simulate the user input.

**Comment by vbfox** [comment]
Hi,

Both are obsolete and were replaced by SendInput (That is already there : https://github.com/AArnott/pinvoke/blob/b597a865739ec0a5223deab913e87a1614f302fb/src/User32.Desktop/User32.cs#L683 )

But you can do a PR to add them if you want, even if obsolete it'll fill the gap in User32 export coverage.

**Comment by h82258652** [comment]
Thanks for response, finally I found Windows Input Simulator: https://www.nuget.org/packages/InputSimulator/
It is easy to use, I think I can close this issue now.
