### ISSUE TITLE
Codegen should not duplicate overloads

### ISSUE THREAD

**Issue by arlm** [AArnott/pinvoke#290]
On #285 [comment #78383434](https://github.com/AArnott/pinvoke/pull/285#r78383434) we discuss a problem in which the generator duplicates the `IntPtr` overload if the function has two overloads with pointers with different types on the same parameter. It should check if the there is already an `IntPtr` overload and then skip on the second instance.

Here is the sample code:

``` cs
[DllImport(nameof(User32), SetLastError = true)]
public static extern unsafe bool GetMonitorInfo(
   IntPtr hMonitor,
   [Friendly(FriendlyFlags.Out | FriendlyFlags.Optional)] MONITORINFO* lpmi);

[DllImport(nameof(User32), SetLastError = true)]
public static extern unsafe bool GetMonitorInfo(
   IntPtr hMonitor,
   [Friendly(FriendlyFlags.Out | FriendlyFlags.Optional)] MONITORINFOEX* lpmi);
```

**Comment by AArnott** [comment]
Closing due to a workaround being available or lack of popular demand. This allows us to better focus on high impact issues. If you feel this is blocking you, you may add a comment here to explain why this should be prioritized.

Thank you for your understanding.
