### ISSUE TITLE
Codegen should treat properly [In | Out] and [Optional] void* pointers

### ISSUE THREAD

**Issue by arlm** [AArnott/pinvoke#292]
An example is:

``` cs
[DllImport(api_ms_win_service_management_l2_1_0, SetLastError = true, CharSet = CharSet.Unicode)]
[return: MarshalAs(UnmanagedType.Bool)]
public static unsafe extern bool ChangeServiceConfig2(
   SafeServiceHandle hService,
   ServiceInfoLevel dwInfoLevel,
   [Friendly(FriendlyFlags.Out | FriendlyFlags.Optional)] void* lpInfo);
```

The friendly code generated on these cases is:

``` cs
public static unsafe bool ChangeServiceConfig2(SafeServiceHandle hService, ServiceInfoLevel dwInfoLevel, ref void? lpInfo)
{
   void lpInfoLocal = lpInfo.HasValue ? lpInfo.Value : default(void);
   bool result = ChangeServiceConfig2(hService, dwInfoLevel, lpInfo.HasValue ? &lpInfoLocal : null);

   if (lpInfo.HasValue)
      lpInfo = lpInfoLocal;

   return result;
}
```

which gives us errors because there is no void type to use without a pointer. I propose we either skip this friendly code generation or we generate this instead on these cases:

``` cs
public static unsafe bool ChangeServiceConfig2<T>(SafeServiceHandle hService, ServiceInfoLevel dwInfoLevel, ref T? lpInfo)
   where T : struct
{
   IntPtr lpInfoLocalPtr = IntPtr.Zero;
   GCHandle? gch = null;
   bool isStruct = false;

   try
   {
      T lpInfoLocal = lpInfo.HasValue ? lpInfo.Value : default(T);
      var type = typeof(T);

      if (type.IsEnum || type.IsPrimitive)
      {
         gch = GCHandle.Alloc(lpInfoLocal, GCHandleType.Pinned);
         lpInfoLocalPtr = gch.Value.AddrOfPinnedObject();
      }
      else
      {
         var layoutKind = type.StructLayoutAttribute?.Value ?? LayoutKind.Auto;
         isStruct = layoutKind == LayoutKind.Explicit || layoutKind == LayoutKind.Sequential;

         if (isStruct)
         {
            var iSizeOfTestStructSimple = Marshal.SizeOf(typeof(T));
            lpInfoLocalPtr = Marshal.AllocHGlobal(iSizeOfTestStructSimple);
            Marshal.StructureToPtr(gch, lpInfoLocalPtr, false);
         }
         else
            throw new ArgumentException("struct should have either LayoutKind.Explicit or LayoutKind.Sequential");
      }

      bool result = ChangeServiceConfig2(hService, dwInfoLevel, lpInfo.HasValue ? (void*)lpInfoLocalPtr : null);

      if (lpInfo.HasValue)
         lpInfo = lpInfoLocal;

      return result;
   }
   finally
   {
      if (gch.HasValue)
         gch.Value.Free();

      if (isStruct)
         Marshal.FreeHGlobal(lpInfoLocalPtr);

      lpInfoLocalPtr = IntPtr.Zero;
   }
}
```

**Comment by AArnott** [comment]
Thanks for the proposed fixes. I would be inclined to go with the first option for now (not generating anything). The second option would need a thorough review that I don't have time for at the moment and may not even be qualified to say for sure works without memory leaks, etc. 
Now regardin the first option, does that even really need a fix? If the desired behavior is to no-op, why add (or allow) the Friendly attribute on that parameter in the first place? At least, we could remove the attribute from the method that fails to be regenerated and it's done. At most, we could cause the generator to emit an error telling the user the attribute isn't supported on `void*` parameters instead of generating an invalid method.

**Comment by arlm** [comment]
Well I think someone might put it not knowing the expected end-result, as I did.  ;-)

Anyway, this way we can map all the pointers matching their proper declaration and when (and if) we want to offer new overloads, we just change the CodeGenerator. I think it is best for us to have a straight policy to map stuff and we decide what and how to offer friendly overloads when we feel it's necessary.

**Comment by AArnott** [comment]
Closing due to a workaround being available or lack of popular demand. This allows us to better focus on high impact issues. If you feel this is blocking you, you may add a comment here to explain why this should be prioritized.

Thank you for your understanding.
