### ISSUE TITLE
.NET 3.5 support

### ISSUE THREAD

**Issue by NN---** [AArnott/pinvoke#305]
Any possibility to support .NET 3.5 ?

**Comment by AArnott** [comment]
I'm not sure. Lacking anything else you can always copy and paste the methods you need into your 3.5 project. 
We might be able to add support conveniently with the new project types in Dev15. I'll look into that. 

Can you share your scenario that need 3.5? Just curious.

**Comment by NN---** [comment]
My project is built with .NET 3.5.
It is a product decision and while we support Windows 7 and .NET 3.5 is supported by MS , I doubt it will change.

**Comment by AArnott** [comment]
I didn't think .NET 3.5 was supported by MS any more. In fact I heard 4.0 wasn't either. (at least not without a special long-term support contract).

Anyway, good news: Dev15's new multi-targeting project type supports net35. So this should make it much more manageable to add another target framework to PInvoke -- when it's mature. Dev15 RC is still a bit rough in this area.

**Comment by NN---** [comment]
https://support.microsoft.com/en-us/gp/framework_faq/en-us

**Comment by AArnott** [comment]
#314 will help us deliver on this quite easily.
