### ISSUE TITLE
WriteProcessMemory

### ISSUE THREAD

**Issue by Mikaka27** [AArnott/pinvoke#308]
Hi,

Is the WriteProcessMemory function not added? I cannot find it.
I mean this one: https://msdn.microsoft.com/pl-pl/library/windows/desktop/ms681674(v=vs.85).aspx

Neither ReadProcessMemory is visible in Kernel32 namespace, are they not added or I'm missing something?

**Comment by AArnott** [comment]
I suspect they haven't been added.
