### ISSUE TITLE
Add SourceLink to the build

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#315]
Blocked by https://github.com/ctaggart/SourceLink/issues/156

**Comment by ctaggart** [comment]
No longer blocked. Upgrade to 2.0.2.

**Comment by AArnott** [comment]
Thanks, @ctaggart. Already working to [verify on appveyor](https://ci.appveyor.com/project/AArnott/pinvoke/build/1.0.1098) with f8cfa6f7552.

**Comment by AArnott** [comment]
Well, that one is going to fail, evidently because at least the test projects don't build with portable PDBs by default. I'll work to fix that.

**Comment by AArnott** [comment]
Fixed by a42927509dbf4b7b4f7b870ebab6d1880cdb45b8
