### ISSUE TITLE
Wrong package versions required?

### ISSUE THREAD

**Issue by thomas-goerlich** [AArnott/pinvoke#318]
The current nuget packages (v0.5.60) have dependencies to other PInvoke packages requiring version >= 1.0.0 but 0.5.60 is the latest version.

e.g.
PInvoke.NCrypt (current version 0.5.60) requires PInvoke.BCrypt, PInvoke.Kernel32 and PInvoke.Windows.Core >= 1.0.0 but only 0.5.60 exists.

**Comment by Bluebeerd** [comment]
I've just spent 2 hours trying to get the update for 0.5.60 installed, so I'm having the same problem.
I can install the update if I disable the dependency checking.
0.4.10 installs fine.

**Comment by AArnott** [comment]
Oops. You're absolutely right.
This is an occurrence of NuGet/Home#4790. And I have a workaround which I will apply right away.
