### ISSUE TITLE
Last error needs to be cleared for functions where NULL return is not necessarily an error

### ISSUE THREAD

**Issue by gabbyzhat** [AArnott/pinvoke#329]
Example of a NULL that may be returned on success: [GetWindowTextLength](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633521(v=vs.85).aspx)

It seems that the `User32.GetWindowText` can cause an erroneous exception by the following:

Steps to reproduce:

1. Call something that may potentially set an error, such as `Console.WriteLine` ([Example](https://i.imgur.com/hBvtf74.png))
2. Call `User32.GetWindowText` on a Window with an empty string title.
3. The `GetWindowTextLength` returns 0, which can either mean an error or empty string
4. [User32.GetWindowText](https://github.com/AArnott/pinvoke/blob/master/src/User32/User32.Helpers.cs#L315) interprets this as a potential error and checks the last error
5. `User32.GetWindowText` sees the error code that was set by calling `Console.WriteLine`  prior and misinterprets this as an error of `GetWindowTextLength`, throwing an exception. This is because [successful calls don't set the error value](https://stackoverflow.com/a/13032390/5343587).

Solution:

Whenever it is possible that the last error may be misinterpreted, call [SetLastError](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680627(v=vs.85).aspx) and clear it, so an empty string can be distinguished from an error. [Example](https://imgur.com/a/LH1ct)

**Comment by AArnott** [comment]
Thanks for the report and suggested fix, @AkariAkaori. That's very insightful, and I agree we should fix up all our helper methods to follow this pattern when the ambiguity exists.

**Comment by AArnott** [comment]
@AkariAkaori I couldn't repro the bug you referred to. I added tests to verify the appropriate behavior even if `GetLastError != 0` going into a `GetWindowTextLength` call and in those tests, the last error is always reset to 0 when the resulting length is 0. 
What version of Windows and .NET Framework did you have installed when you saw this fail? Or did you not see this fail but theorized the problem may exist?

**Comment by gabbyzhat** [comment]
I was getting exceptions when I iterated over all windows searching for a window whose text matched a regex with PInvoke.User32 v4.0.30319 targetting NET Framework 4.7 on Windows 10 64-bit enterprise

When I made an implementation that reset the error when appropriate, the exceptions stopped. The thing I noticed is that it only crashed when I called certain IO operations in .NET like Console.WriteLine (cant remember the specific functions I called but this is the general idea)

Crash after the first iteration:
```
foreach(var window in enumerateWindows)
   Console.WriteLine(window.GetWindowText())
```

No crash because texts are evaluated before calling Console:
```
foreach(var windowText in enumerateWindows.Select(x => x.GetWindowText()).ToArray())
    Console.WriteLine(windowText);
```

**Comment by AArnott** [comment]
Reopening per [@AkariAkaori's repro](https://github.com/AArnott/pinvoke/pull/338#issuecomment-316564678).

**Comment by ghost** [comment]
BTW, using CER/`RuntimeHelpers.PrepareContrainedRegions` referenced in #338 seems to work well for the `GetWindowText` helper (I just tried it out). It's certainly a big improvement over the native-module approach outlined by me in #388.
