### ISSUE TITLE
CreateWindowEx (user32)

### ISSUE THREAD

**Issue by tqk2811** [AArnott/pinvoke#345]
How about this?
```
[DllImport("user32.dll", SetLastError = true, EntryPoint = "CreateWindowEx")]
public static extern IntPtr CreateWindowEx(
       int dwExStyle,
       UInt16 regResult,
       string lpWindowName,
       UInt32 dwStyle,
       int x,
       int y,
       int nWidth,
       int nHeight,
       IntPtr hWndParent,
       IntPtr hMenu,
       IntPtr hInstance,
       IntPtr lpParam);
```
Then in your lib, how i can use `....(int dwExStyle, string lpClassName,string lpWindowName,....` as this?
The different is `UInt16 regResult` and  `string lpClassName` (regResult from return of RegisterClassEx)
I was tested, `UInt16 regResult` is running  success

**Comment by AArnott** [comment]
I don't understand the question. Are you proposing a new overload, or asking how to use an existing one?

**Comment by tqk2811** [comment]
your code doesn't support that 
```
public static extern IntPtr CreateWindowEx(
       int dwExStyle,
       UInt16 regResult,//string lpClassName
       string lpWindowName,
       UInt32 dwStyle,
       int x,
       int y,
       int nWidth,
       int nHeight,
       IntPtr hWndParent,
       IntPtr hMenu,
       IntPtr hInstance,
       IntPtr lpParam);
```
[code](https://github.com/tqk2811/InterprocessCommunications/blob/4ba5aa843b4b5fc955087debae774abe7cbe05d3/Interprocess%20Communications%20(%20IPC%20)/IC_WindowMessage/MessageOnlyWindows.cs)

**Comment by vbfox** [comment]
Yes we're missing the overload where `lpClassName` is an `ATOM`. Sounds like a good contribution for a PR.

**Comment by vbfox** [comment]
Reflecting a little on it the tricky question is what should be the type in the overload.

`ATOM` is documented as Int16-sized and it kinda "works" when specified like that but it's only an accident of calling convention as it's one of the first args to the functions and registers are used for them. If it was on the stack it would blow completely.

But it doesn't blow and all current windows archs (x86, x64, arm) are using registers for the second argument...

The correct one is `IntPtr` (Signature is `LPCTSTR`) but it's a little bit more annoying to call as it would require a cast.

I would be in favor of `IntPtr` as it's more correct. What do you think @AArnott ?

**Comment by AArnott** [comment]
Thanks, @vbfox. How about a private pinvoke method with IntPtr and then expose a public overload that calls the DllImport version and takes a `short`?

**Comment by vbfox** [comment]
Perfect, don't know why I didn't think about it.
