### ISSUE TITLE
User32.AttachThreadInput(...) doesn't exist

### ISSUE THREAD

**Issue by BarryNolte** [AArnott/pinvoke#347]
It appears this API was overlooked.

**Comment by AArnott** [comment]
We didn't overlook it. We just haven't defined it yet. PInvoke doesn't have an exhaustive set of methods yet. You're welcome to send a PR if you'd like. Just check out the contrib doc first.

**Comment by BarryNolte** [comment]
I added this back in October. Submitted for tracking purposes only.
