### ISSUE TITLE
Method not found in a specific ApiSet

### ISSUE THREAD

**Issue by jomonson** [AArnott/pinvoke#350]
I'm getting "Unable to find an entry point named 'CreateProcess' in DLL 'api-ms-win-core-processthreads-l1-1-1.dll". 

First I didn't even find the dll in my system. I've installed vcredist 2015 and then found it in System32 folder.
There, I used "dumpbin /exports api-ms-win-core-processthreads-l1-1-1.dll" to find out that it doesn't have CreateProcess method exported.

Besides, I don't understand why specific ApiSets are used in the attribute of the method signatures (DllImport).

I'm getting this when using PInvoke.Kernel32 version 0.5.86.

Edit: It happens in OS Windows 2008 R2

**Comment by AArnott** [comment]
Windows API sets [are only supported on Win8 and Windows Server 2012 and later](https://msdn.microsoft.com/en-us/library/windows/desktop/dn505783(v=vs.85).aspx).

Can I ask which target framework your app is targeting? Is it net40, net20, net45, etc?

**Comment by jomonson** [comment]
The target framework is .Net Framework 4.6.1

**Comment by jomonson** [comment]
Is there a fix coming up?

**Comment by AArnott** [comment]
Yes. Working on it now.
