### ISSUE TITLE
API's implemented in headers

### ISSUE THREAD

**Issue by ghost** [AArnott/pinvoke#357]
Consider [IsWindowsVersionOrGreater](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424964(v=vs.85).aspx). 

Where should something like this be implemented ? 

- In a new class (`VersionHelpers.dll`) ? 
- In `Windows.Core`, as a new type (`PInvoke.VersionHelpers`, exposed via `Windows.Core`)? 
- Nowhere - it's not, strictly speaking, `PInvoke` - so take it over to a more apt project like [WinApi](https://github.com/arlm/WinApi)
- some other recommendation ?

**Comment by AArnott** [comment]
I think WinApi is a fine choice. If the header file it comes from maps directly to one of the libraries for which we have p/invokes, I don't think I'd object to defining it in one of our libraries though.
