### ISSUE TITLE
GetCurrentThreadId will faill on some machines where it missing from api-ms-win-core-processthreads-l1-1-1.dll

### ISSUE THREAD

**Issue by garg0v** [AArnott/pinvoke#358]
I am trying to use GetCurrentThreadId() but on some machines I get : 
(ERROR) Unexpected exception has occurred  System.EntryPointNotFoundException: 
Unable to find an entry point named 'GetCurrentThreadId' in DLL 'api-ms-win-core-processthreads-l1-1-1.dll'. caught here: PInvoke.Kernel32.GetCurrentThreadId() 
Is there a reason for using that library instead of kernel32.dll?

**Comment by AArnott** [comment]
We use the "API Sets" DLLs as required to work in Store apps, when the apps are targeting store-compatible profiles.
What version of Windows are you using?
What version of PInvoke are you using?
What is the target platform of your app, and the target platform of the library that references PInvoke? Which PInvoke.Kernel32.dll within the nuget package is your app shipping?

**Comment by AArnott** [comment]
Closing due to no response.
