### ISSUE TITLE
What about EnumProcesses in Psapi

### ISSUE THREAD

**Issue by ghost** [AArnott/pinvoke#359]
Hello,

when I found this huge library I was looking for a special function in particular: EnumProcesses in psapi.
I can see, that this function is not implemented yet. Will it never be implemented or will it come in some time?

Thanks in advance.

**Comment by AArnott** [comment]
Hi @Yothri. This project isn't exhaustively implemented yet. We grow by request, and especially by *pull* request. :)

We would welcome a PR from you to add this method.

**Comment by ghost** [comment]
Allright, thanks for the fast answer. I already put another Pull Request for GetProcessId() in Kernel32.
I am going to add EnumProcesses then if I got it working and tested.

Best Regards
