### ISSUE TITLE
BCryptDeriveKeyPBKDF2 not included

### ISSUE THREAD

**Issue by davidmurdoch** [AArnott/pinvoke#375]
https://msdn.microsoft.com/en-us/library/windows/desktop/dd433795(v=vs.85).aspx

**Comment by AArnott** [comment]
Sounds related to #365

**Comment by davidmurdoch** [comment]
the `BCryptKeyDerivation` function is included but not in the tests. `BCryptDeriveKeyPBKDF2` implementation isn't included (but still appears in BCrypt.exports.txt).
