### ISSUE TITLE
PInvoke.Windows.Core version 0.5.134 missing

### ISSUE THREAD

**Issue by Argante80** [AArnott/pinvoke#379]
I'm trying to update the packages PInvoke.Kernel32 and PInvoke.BCrypt to the version 0.5.134 but they require the same version of the PInvoke.Windows.Core library that is not available yet.

**Comment by AArnott** [comment]
Thanks for reporting this. The 0.5.134 deployment from Appveyor failed midway through, it seems.

**Comment by AArnott** [comment]
It looks like retrying the deployment just resumed it. :) Windows.Core is now published (and validating on nuget.org).
