### ISSUE TITLE
Provide a meta-package in NuGet

### ISSUE THREAD

**Issue by vbfox** [AArnott/pinvoke#38]
I'm thinking of a package in the same spirit as [Microsoft.CodeAnalysis](https://www.nuget.org/packages/Microsoft.CodeAnalysis) or [xunit](https://www.nuget.org/packages/xunit) that could be named `PInvoke`

One consideration is that for now the library contains only pinvoke for windows dlls (delivered with the operating system) so the package would be named more exactly `PInvoke.Windows`.

The main advantage for the package I see is for easy prototyping (For example in LINQPad) where searching beforehand for all necessary packages might be more complex than just referencing a meta package.

What do you think ?

**Comment by AArnott** [comment]
Sounds good to me.
If we do this, we should update the addproject.ps1 script (or whatever it's called) to prompt the user to add a project reference to the nuget project.

**Comment by AArnott** [comment]
Given that this project may evolve to include non-Win32 libraries, I wonder if we should call such a metapackage `PInvoke.Win32`.
