### ISSUE TITLE
SetWindowLongPtr on 32-bit

### ISSUE THREAD

**Issue by ghost** [AArnott/pinvoke#385]
[This is an issue about my recent PR [384](https://github.com/AArnott/pinvoke/pull/384)]

According to the documentation for [SetWindowLongPtr](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644898(v=vs.85).aspx), 

>  When compiling for 32-bit Windows, SetWindowLongPtr is defined as a call to the SetWindowLong function.

What this really means is that calls to `PInvoke.User32.SetWindowLongPtr` on 32-bit processes will (and do) result in an `EntryPointNotFoundException`

Thoughts on how to, or whether to, fix this? 

I feel like this should be fixed, by exposing `SetWindowLongPtr `through `User32.Helpers.cs` and conditionally calling `SetWindowLongPtr `on 64-bit vs. `SetWindowLong `on 32-bit. 

If no objections, I'll submit another PR.

**Comment by AArnott** [comment]
Thanks for catching that. Your proposal for a helper method sounds reasonable. The only alternative would be to dual-compile the library for x86 and x64 and I'd rather avoid doing that.

**Comment by ghost** [comment]
I have a [pull request ](https://github.com/AArnott/pinvoke/pull/387) out for this.
