### ISSUE TITLE
Missing GetWindowLongPtr in Package

### ISSUE THREAD

**Issue by YauronBis** [AArnott/pinvoke#389]
I was suprised about this missing in User32 class.
I get an exception because of x64 handle.
On P/Invoke web site, you wrote a sub to abstract x32/x64 GetWindowLong depending on IntPtr.Size.
But not inclued into Package too.

**Comment by AArnott** [comment]
We don't typically release after every individual change, and we've only had two changes since our 0.5.147 release. But since you hit it and want it, I'm happy to oblige.

0.5.152 is being pushed to nuget.org right now.
