### ISSUE TITLE
Missing from this project - Need Smart Device APIs from pinvoke.net 

### ISSUE THREAD

**Issue by sfitzge308** [AArnott/pinvoke#390]
With PInvoke.Net currently down, I am at a loss for even the documentation for these dlls. Does anyone have it? 

  Smart Device Functions:
 aygshell.dll
 coredll.dll
 ipaqutil.dll
 rapi.dll

**Comment by AArnott** [comment]
Good news in the short-term is that [pinvoke.net is back up](https://downforeveryoneorjustme.com/pinvoke.net) :smile:.

I'd love to see these libraries added to this project. We achieve this primarily by community contributions so we'd welcome your help with that.

**Comment by sfitzge308** [comment]
Yes thank God it is back up.. I am really in a pickle without that site from time to time.. I should devise some way to export that information in an automated fashion..  any ideas?

**Comment by ghost** [comment]
Tried http://web.archive.org/web/20180224034348/http://pinvoke.net/?

**Comment by sfitzge308** [comment]
Yes, I did that, and the home page appears, but the expanders along the left side are just linking me back to the home page. There is really a ton of info in there and it may not be crawlable, or it’s just too big for wayback machine to handle.
Thanks for the suggestion, though..
