### ISSUE TITLE
Switch to non-static classes for namespacing.

### ISSUE THREAD

**Issue by ghost** [AArnott/pinvoke#391]
There are two deficiencies in the C# language:
1. A namespace can not contain members.
2. A static class is automatically sealed.

The first issue necessitates the use of classes to hold symbolic constants, enumerations, and methods. The second prevents those namespace classes from being easily extended with user code. This means that there is no easy way for users to add functionality missing from PInvoke to their projects in a consistent way.

Namely it is not possible to do the following with the classes provided by PInvoke:
```c#
namespace Project
{
    class Program
    {
        static void Main(string[] args)
        {
            B.m();
        }
    }

    class A
    {
        public static void m()
        {

        }
    }

    class B : A
    {
        public static void n()
        {

        }
    }
}
```

Since it is unlikely the necessary features will be added to C# it seems more prudent to change the type of class used for namespacing in PInvoke.

There are some unpleasant effects:
1. `B.m()` produces a hint about a name which can be simplified.
2. You can't call `super` from a static method so overridden methods would need to reimplemented in full.

Cheers,
     R0b0t1

**Comment by AArnott** [comment]
Using non-static classes would preclude the use case of:

```cs
using static PInvoke.User32;

OpenHandle(something);
```

The ability to use the members of the class directly make C# p/invokes about as easy or easier than in C++ even.  But if we switch to non-static classes I think this wouldn't work. 

Regarding your desire to extend PInvoke, can you send PRs to add it to the project?

**Comment by ghost** [comment]
That is a good point and may outweigh the short term benefit of being able to mix in custom methods. At the same time, it is possible to give the `using` clause a short name.

It looks like this would require a language-level fix.

**Comment by HaloFour** [comment]
@AArnott 

> Using non-static classes would preclude the use case of

Actually `using static` doesn't require that the class be marked `static`.

**Comment by ghost** [comment]
It looks like there's no detriment to doing this. [This comment](https://github.com/dotnet/csharplang/issues/1631#issuecomment-397623264) shows another use for the pattern.

It might be good to implement an empty constructor for each class which throws `NotImplementedException` to keep people from instantiating them. At the same time, even if they did, there's nothing they actually do.

**Comment by AArnott** [comment]
We don't need to implement the ctor with a throw. We could just define a private default constructor, which would block anyone from instantiating it even at compile time.

**Comment by dzmitry-lahoda** [comment]
I tried to define [private default constructor in other case](https://github.com/dotnet/csharplang/issues/1631#issuecomment-456161043) and it did not work.

**Comment by AArnott** [comment]
Unsealing to allow someone to derive doesn't unlock anything except to refer to the original methods under a different class name. Deriving a class would only accomplish that, and I see little to no value in doing so.
