### ISSUE TITLE
Improve our API coverage doc

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#407]
Our README points to [a *downloadable* html file](https://ci.appveyor.com/api/projects/aarnott/pinvoke/artifacts/coverage.html?branch=master) that appveyor produces to report on our API coverage. This is a clunky UX. 

[This stylecop.analyzers experience](https://dotnetanalyzers.github.io/StyleCopAnalyzers/) is much better, and is similarly produced in part by appveyor. @sharwell developed this. 

We should do something nice like that. :)

**Comment by sharwell** [comment]
📝 @pdelvo created the original data extraction tool and presentation theme. My only part was moving it from dedicated hosting to AppVeyor/GitHub Pages. 😄

**Comment by AArnott** [comment]
We now keep our exports as extra files in each github release. Folks haven't really complained, so I'm closing this.
