### ISSUE TITLE
ReadFile/WriteFile OVERLAPPED tests should use Pipes

### ISSUE THREAD

**Issue by vbfox** [AArnott/pinvoke#41]
See #40 for some background.

The current tests use files but we have no way to control whenever the IO will really be asynchronous or not, we should use pipes instead where we can ensure that a synchronous answer is impossible.

It would also allow to correctly test IO Cancelation support.

I implies adding support for [`CreatePipe`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365152) or [`CreateNamedPipe`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365150.aspx).

**Comment by AArnott** [comment]
Sounds good. :)

**Comment by AArnott** [comment]
We now seem to have all the prerequisites mentioned.
