### ISSUE TITLE
PostMessage with fully custom wMsg in  User32 PostMessage

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AArnott/pinvoke#423]
In order to implement windows hook I need to pass custom not known windows message. Example of such usage would be WPF Dispatcher which passes pseudo random value in order to have such hook. Would you accept this kind of pull?

```
     [DllImport(nameof(User32), SetLastError = true, CharSet = CharSet.Unicode)]
        [return: MarshalAs(UnmanagedType.Bool)]
public static extern unsafe bool PostMessage(IntPtr hWnd, uint wMsg, void* wParam, void* lParam);
```

I found issue during migrating my code onto this lib.

**Comment by AArnott** [comment]
Do you know that you can use custom messages already simply by casting your custom uint value to a `WindowMessage` enum?
