### ISSUE TITLE
Need test for ChangeServiceConfig2 with ServiceFailureActions

### ISSUE THREAD

**Issue by icnocop** [AArnott/pinvoke#425]
Hi.

Thank you for the PInvoke libraries.

The `ServiceFailureActions` structure has an array of `ServiceControlAction`s and this seems to cause issues when trying to pass it to `ChangeServiceConfig2`.

When I try, I get the following exception: "PInvoke.Win32Exception (0x80004005): The parameter is incorrect".

All the code examples I've seen that use `IntPtr` instead of an array work without issues.

Thank you.

**Comment by AArnott** [comment]
How would we test it? Can this method be called outside of a Windows Service?

**Comment by AArnott** [comment]
I suspect the problem here isn't the array -- it's probably the `string` fields. But anyway this struct doesn't follow any of our current guidelines so I'm rewriting them...
