### ISSUE TITLE
Support pseudo console api

### ISSUE THREAD

**Issue by ghost** [AArnott/pinvoke#430]
As of RS5 kernel32.dll now has the following three methods

- [`CreatePseudoConsole`](https://docs.microsoft.com/en-us/windows/console/createpseudoconsole)
- [`ResizePseudoConsole`](https://docs.microsoft.com/en-us/windows/console/resizepseudoconsole)
- [`ClosePseudoConsole`](https://docs.microsoft.com/en-us/windows/console/closepseudoconsole)

**Comment by Alikont** [comment]
[Sample from Microsoft](https://github.com/microsoft/terminal/tree/master/samples/ConPTY/MiniTerm/MiniTerm/Native) in terminal repo.
