### ISSUE TITLE
Fix EntryPoints for MoveMemory, CopyMemory, FillMemory, ZeroMemory

### ISSUE THREAD

**Issue by vatsan-madhavan** [AArnott/pinvoke#431]
Please see https://github.com/dotnet/coreclr/issues/24008 for background.

.NET Framework has special case logic to ensure that `MoveMemory`, `CopyMemory`, `FillMemory`, and `ZeroMemory` are correctly mapped to `RtlMoveMemory`, `RtlCopyMemory`, `RtlFillMemory`, and `RtlZeroMemory` respectively. 

.NET Core does not have this this special case, so the following P/Invoke definition will fail on .NET Core. 

```C#
    [DllImport("kernel32.dll", EntryPoint = "CopyMemory", SetLastError = false)]
    public static extern void CopyMemory(IntPtr dest, IntPtr src, uint count);
```

At least two definitions in `PInvoke.Kernel32` are likely to fail in .NET Core - [`MoveMemory`](https://github.com/AArnott/pinvoke/blob/f33390258e555bee510ac0216290f34456e5c6d1/src/Kernel32/storebanned/Kernel32.cs#L2308), and `CopyMemory`. (I did not inspect to see whether `FillMemory` and `ZeroMemory` have this bug).

**Comment by AArnott** [comment]
`FillMemory` and `ZeroMemory` are macros that are defined in terms of `memset` rather than a native exported function from a Win32 DLL. I will fix `MoveMemory` and `CopyMemory` though.

Thanks for the report.

**Comment by hugmyndakassi** [comment]
While it is technically true that these are macros in the header, `kernel32.dll` has long exported `RtlZeroMemory` as function forwarder into a function of the same name in `ntdll.dll` and also provides an exported `RtlFillMemory` function.

As a side-note, [Vanara](https://github.com/dahall/Vanara) also relies on these four functions existing in `kernel32.dll`.

**Comment by AArnott** [comment]
@hugmyndakassi Are `RtlZeroMemory` or `RtlFillMemory` as exported functions documented? I can't find any documentation for them outside of macros. We don't expose undocumented Windows features in this library.

**Comment by mpolicki** [comment]
I'll just leave a quick note here that I got a `System.EntryPointNotFoundException: 'Unable to find an entry point named 'RtlCopyMemory' in DLL 'Kernel32'.` in a unit test with a `CopyMemory` call. The exception went away after I set `Processor Architecture for AnyCPU Projects` to `x64` in Visual Studio Test Explorer settings.

.NET Framework 4.7.2, PInvoke 0.7.104

**Comment by AArnott** [comment]
Thanks, @mpolicki. To be clear, it sounds like you're saying that x86 processes don't get a kernel32 export of RtlCopyMemory, but x64 processes do. Does that sound about right? If so, can you open a separate issue to track that?

**Comment by mpolicki** [comment]
@AArnott Yes, that's exactly what seems to be the case. The issue is #587.

**Comment by AArnott** [comment]
Thank you.
