### ISSUE TITLE
Drop targeting all but netstandard2.0, uap10.0, and net45

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#435]
Microsoft's long-term support for .NET Core 1.x and 2.0 [are over](https://github.com/dotnet/core/blob/e2f22a7106860c0e5dc98bb36dc648a779944ad5/microsoft-support.md#net-core-releases). Customers targeting these versions are in a really bad place due to no security patches being offered and thus there are likely few to none out there.

Similarly, such a critical mass of customers already have net472 on their machines that many apps and libraries now support it.

PCLs (e.g. `portable-net40+win8+wpa81`) have not been createable in VS for years as well.

This means we can likely target just netstandard2.0 (and UWP to retain our Store app compliance).

**Comment by AArnott** [comment]
@vbfox @arlm @jmelosegui Comments or concerns?

**Comment by arlm** [comment]
Makes complete sense for me.

Andrew Arnott <notifications@github.com> schrieb am So., 7. Juli 2019,
14:25:

**Comment by vatsan-madhavan** [comment]
I had a  hard time building the repo recentlly - had to download an archived copy of Win8 SDK to get a clean build. I may have had to install some netfx dev pack as well.. glad this is being considered.

**Comment by AArnott** [comment]
In 9bf33aeecb9 I dropped the PCL profiles from all projects. I dropped net40 from all but one project (only one project actually needed it). 
I also dropped win8 support because VS2019 has a bug(?) where it can't build them even with the Win8 SDK installed. In place of win8 I target uap10.0.

The CONTRIBUTING.md doc is updated with instructions to get it to build. I've tested it on a very clean Win10 machine (using Win10's Sandbox VM) so I believe it should all work.

I haven't yet dropped net20 support. I might do that. I'll wait to hear if there are screams from just dropping net40 or PCLs or Win8 before cutting more.

**Comment by qmfrederik** [comment]
re: `net20`: I couldn't find any hard numbers, but it looks like Windows 7 is the oldest Windows version which is still relevant. .NET 4.x should be delivered to that OS via Windows Update. So I'd say it's safe to assume NET 4.x is a good baseline.

**Comment by AArnott** [comment]
Yes, for all except embedded medical devices which tend to be many years behind everyone else. But then, they probably won't be consuming these nuget packages directly anyway, and they can always copy and paste the code they need. So ya, let's do it.

**Comment by vatsan-madhavan** [comment]
OTOH now there are netfx ref assemblies available on NuGet that seem to work reliably. Not discouraging this move - just pointing out an option. 

https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net20/

**Comment by AArnott** [comment]
@vatsan-madhavan We already use these:

https://github.com/dotnet/pinvoke/blob/4a256494e38e8fff02113dbc4d9bd2f3b78435d1/src/Directory.Build.props#L82

But I'm not sure what that has to do with the discussion. We're not dropping net20 support for lack of ref assemblies. The build is quite slow, and the design-time experience in VS is rather sluggish and memory heavy as well. Reducing the TFMs we support make development that much better.

While dropping `netstandard1.x` support seems to make sense, dropping `net20` is probably a little more debatable. Still, I'm open to all arguments for and against.

**Comment by AArnott** [comment]
We're keeping `net45` for now. `netstandard2.0` and `uap10.0` are also still around per proposal. 
The rest are gone.
