### ISSUE TITLE
Missing GetMenu (user32)

### ISSUE THREAD

**Issue by Anton-V-K** [AArnott/pinvoke#437]
I see no [`GetMenu`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmenu) in User32.
Is it available in some other namespace?

BTW only one menu-related function `GetMenuItemInfo` is available. It would be helpful to have access to other functions as well.

**Comment by AArnott** [comment]
Boy, `MENUBARINFO` is a tricky structure to encode as C#. :)
