### ISSUE TITLE
GCM Example

### ISSUE THREAD

**Issue by lellis1936** [AArnott/pinvoke#441]
AES GCM is rightfully becoming very popular; perhaps an example would be useful to include somewhere in the project?

As an aside, I've created a Gist for GCM with this library: https://gist.github.com/lellis1936/4a0904f2029682583e93b27dfb2082c0

**Comment by VaslD** [comment]
Just want to note that AES GCM is available in *System.Security.Cryptography* [as of .NET Standard 2.1](https://docs.microsoft.com/dotnet/api/system.security.cryptography.aesgcm?view=netstandard-2.1) as an alternative to P/Invoking.

**Comment by lellis1936** [comment]
> Just want to note that AES GCM is available in _System.Security.Cryptography_ [as of .NET Standard 2.1](https://docs.microsoft.com/dotnet/api/system.security.cryptography.aesgcm?view=netstandard-2.1) as an alternative to P/Invoking.

Thanks for this.  Good to know but I'm sure you're aware of the controversy over Microsoft's dropping .Net Framework support as of 2.1.   Too bad, I think that is a bad idea for Microsoft.

**Comment by VaslD** [comment]
I don't like it either. But considering Microsoft is working on unifying all of .NET (.NET 5 and 6) – at least that's what's in the news – I don't see Framework itself getting much love in the future. So it's probably a good choice to migrate to Core now than later. Anyway, like I said, "alternative to P/Invoking".
