### ISSUE TITLE
ShellScalingApi is empty?

### ISSUE THREAD

**Issue by wilversings** [AArnott/pinvoke#449]
Hello

I see that the `ShellScalingApi` from PInvoke.Windows.ShellScalingApi is empty, and does not provide the methods from here https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/

**Comment by AArnott** [comment]
I don't remember why it's factored this way, but ShellScalingApi only defines the enums/structs, while the p/invoke methods themselves are defined in the ShCore project:

https://github.com/dotnet/pinvoke/blob/70384fbcd59e15234b3f1548bd19d194c0486880/src/SHCore/SHCore.cs#L14
