### ISSUE TITLE
User32: make MENUITEMINFO.Create() static

### ISSUE THREAD

**Issue by x1unix** [AArnott/pinvoke#458]
Hello, currently `MENUITEMINFO.Create()` is instance method and if I need to create the struct with correct size, I need to do this:

```csharp
MENUITEMINFO mii = new MENUITEMINFO();
MENUITEMINFO correctMii = mii.Create();
```

Currently, I don't see any advantage of non-static `.Create()` because it doesn't utilize original struct's state:

```csharp
 public MENUITEMINFO Create()
            {
                return new MENUITEMINFO
                {
                    cbSize = Marshal.SizeOf(typeof(MENUITEMINFO))
                };
            }
```

I think that it will be more convenient to make this method static to avoid `mii` declaration (or provide alternative way to initialize the struct):

```csharp
MENUITEMINFO mii = MENUITEMINFO.Create();
```

**Comment by AArnott** [comment]
Ya, that's a bug in the API.
