### ISSUE TITLE
Kernel32.ReadProcessMemory should use SafeObjectHandle

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/pinvoke#487]
`Kernel32.OpenProcess` returns a `SafeObjectHandle`, so it seems logic for `Kernel32.ReadProcessMemory` to accept a `SafeObjectHandle`, too.

**Comment by AArnott** [comment]
Agreed. Let's add an overload for this and add `[Obsolete]` on the existing one to spread out the breaking change.
