### ISSUE TITLE
Add netcoreapp build and run for test projects

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#488]
> Do the netcoreapp version of the tests run by default yet?

No. Last I checked we didn't even have netcoreapp builds of the test projects, but it's probably time to add that.

_Originally posted by @AArnott in https://github.com/dotnet/pinvoke/pull/486#issuecomment-653610887_

**Comment by vatsan-madhavan** [comment]
Hmm... Visual Studio shows me this: 

![image](https://user-images.githubusercontent.com/20246435/86485723-4e5b0080-bd0e-11ea-837b-7c6b879d7fcd.png)

Looks like `Kernel32.Tests.csproj` is multitargeted to `net472;necoreapp2.1`
