### ISSUE TITLE
Enable CA1414 for all projects

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#50]
Per @vbfox's [suggestion](https://github.com/AArnott/pinvoke/commit/5ae033e65a31b8c3590add34de316dcd36f510e4#commitcomment-14348785)

**Comment by vbfox** [comment]
After checking it seem that CA1414 is only in FXCop external analysis and still not ported to the new [FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers) package so we will have to decide to enable it and when (Only in Release/CI builds or on all builds, knowing that it'll slow down builds)

**Comment by AArnott** [comment]
Let's do it: enable Code Analysis on Release builds with at least CA1414 enabled.

Ideally in the process, we consolidate all the .ruleset files to just one or two (for product and test) so we can add/remove rules to apply to all projects.

**Comment by arlm** [comment]
How can this issue have help? What is in need to be done?

**Comment by AArnott** [comment]
Ideally implement the rule in FxCop analyzers then install the package in our projects. But simply enabling legacy FxCop for these projects for this rule would work too. 
Thanks.

**Comment by AArnott** [comment]
CA1414 still hasn't been ported: https://github.com/dotnet/roslyn-analyzers/issues/430

And I'm actually leaning in the opposite direction, since `BOOL` is so common and `U1` so rare, that perhaps we can just drop all the attributes that explicitly state default behavior.
