### ISSUE TITLE
Support Win32 Events

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/pinvoke#514]
Overlapped I/O uses Win32 events to signal the completion of an overlapped I/O operation.
.NET nor PInvoke.Kernel32 provide built-in support for working with Win32 events.

Consider adding support for:
- [`CreateEventEx`](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventexw), [`SetEvent`](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-setevent) and [`ResetEvent`](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-resetevent). There are [P/Invoke declarations in .NET Core](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.EventWaitHandle.cs)
- Asynchronously awaiting events. [Microsoft.VisualStudio.Threading.TplExtensions.ToTask](https://github.com/microsoft/vs-threading/blob/master/src/Microsoft.VisualStudio.Threading/TplExtensions.cs#L457) provides a reference implementation.

Split off from https://github.com/dotnet/pinvoke/pull/513#discussion_r456068538

**Comment by AArnott** [comment]
The p/invokes are fine to add. I'm less convinced we should create and/or expose an `GetAwaiter` extension for `WaitHandle`, particularly since it's already done in a public Microsoft-owned package.
If we needed a copy internally, we could consider that.
