### ISSUE TITLE
WinUsbPipeStream

### ISSUE THREAD

**Issue by qmfrederik** [AArnott/pinvoke#515]
The `WinUsb` API allows you to read/write from USB pipes using `WinUsb_ReadPipe` and `WinUsb_WritePipe`.

It may make sense to provide a `WinUsbPipeStream` helper class which wraps these methods in a `Stream`.

In its most simple form, `WinUsbPipeStream` would wrap around:
- A `WinUsbHandle` which represents the USB device
- A `byte?` which holds the ID of the input pipe (`null` if read-only)
- A `byte?` which hold the ID of the output pipe (`null` if write-only)

- Read/Write would be blocking calls to `WinUsb_ReadPipe`/`WinUsb_WritePipe`
- `ReadAsync`/`WriteAsync` could use overlapped I/O
- This class could cache an instance of the `WinUsbOverlapped` class on _every_ I/O operation

**Comment by AArnott** [comment]
That sounds like a great class, but it's decidedly against the scope of the repo to avoid building up into a "BCL"-like library. It's just supposed to be p/invokes, supporting structs, and very few helper methods. 
Perhaps as a separate nuget package in another repo though? We could even create a list in this repo's README of "useful higher level abstraction libraries that consume this one" with this as its (currently) only item.
