### ISSUE TITLE
Powershell scripts are significantly slowing down the build

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#52]
It turns out that building is a lot slower now. Task Manager shows powershell spending a lot of time during the build. I don't yet know whether it's one of the ps1 scripts with a bad algorithm or (more likely) just spawning powershell.exe itself taking a long time. But we should see what we can do to reduce the time.

**Comment by jmelosegui** [comment]
@AArnott,

I did some benchmarking to the build process and here are the results:

**Tests**
To run the build (from command line) with and without the `Create-PInvokeTxtFile.ps1` script and then with a _dummy_ version of the powersell scrtipt whose sole job is to output a text to the MSBuild log, and hence  removing the reflection algorithm from the build time.

**Hardware**
Processor: Intel Core i7-4712Q CPU @ 2.30GHz 2.30GHz
Memory Ram: 16 GB
System Type: 64-bit OS 

**MSBuild single process**

| Test | Build Time |
| --- | --- |
| with ps script | 26-27 sec |
| without ps script | 14 sec |
| with dummy ps script | 24-25 sec |

**MSBuild concurrent processes (/m switch 8 cores)**

| Test | Build Time |
| --- | --- |
| with ps script | 12-14 sec |
| without ps script | 7-9 sec |
| with dummy ps script | 11-13 sec |

 The fact that MSBuild spawn powershell once per project using the PInvoke.Extra.targets makes the build process time two times slower (regardless of the process time to generate the LIBNAME.pinvokes.txt file).

 We should consider to generate the `LIBNAME.pinvokes.txt` files at the end of the build process, and change the process in such a way that powershell is loaded just one time to generate the files for all dlls.

 Thoughts?

**Comment by AArnott** [comment]
MSBuild doesn't provide a way to do something at the end of a build process like that. But we could remove the Target that does the work from the standard Build pipeline so that you have to run some other target for it to do the work. Alternatively, we could put a Condition attribute on the target itself so that although it's part of Build, it only does something when MSBuild is run from the command line with `/p:GeneratePInvokesTxt=true`. I'm leaning toward that option.
