### ISSUE TITLE
Can't get DwmGetWindowAttribute to work

### ISSUE THREAD

**Issue by Slion** [AArnott/pinvoke#527]
I tried a bunch of stuff including the following all I get is null reference exception thrown by DwmGetWindowAttribute.

            PInvoke.RECT rect = new PInvoke.RECT();
            int size = Marshal.SizeOf(typeof(PInvoke.RECT));
            IntPtr rectPtr = Marshal.AllocHGlobal(size);
            PInvoke.DwmApi.DwmGetWindowAttribute(hwnd, DwmApi.DWMWINDOWATTRIBUTE.DWMWA_EXTENDED_FRAME_BOUNDS,out rectPtr,size);
            Marshal.PtrToStructure(rectPtr, rect);
            Marshal.FreeHGlobal(rectPtr);

It's a lot faster to get it working using that solution:
https://stackoverflow.com/a/58675103/3969362

**Comment by AArnott** [comment]
It looks like we incorrectly use `out` *and* a pointer type, which turns into a double-pointer.

**Comment by AArnott** [comment]
Thanks for reporting, @Slion

**Comment by Slion** [comment]
Congrats on the quick turn around. @AArnott Any chance of having an overload taking RECT as parameter much like on that stackoverflow post linked above?

**Comment by AArnott** [comment]
No.  Our convention is to use the same types used in the native signature. But it shouldn't be hard for you to use RECT.  *Much* easier than your original code nsippet.

Something like this:

```cs
unsafe void Foo()
{
        PInvoke.RECT rect = new PInvoke.RECT();
        PInvoke.DwmApi.DwmGetWindowAttribute(hwnd, DwmApi.DWMWINDOWATTRIBUTE.DWMWA_EXTENDED_FRAME_BOUNDS, &rect, sizeof(rect));
}
```

Don't worry about the 'unsafe' code. It doesn't mean your caller has to be unsafe. And honestly, this way you're not responsible for allocating, freeing, and copying native memory that could leak. C# pointer code is much easier than all this `IntPtr` nonsense that was invented to support poor VB.

**Comment by Slion** [comment]
@AArnott Thanks for that insight. When will that fix make it into a release?

**Comment by AArnott** [comment]
It looks like it's been quite a while, with quite a bit of work, since our last release. I'll go ahead and release to nuget.org today.
