### ISSUE TITLE
HidP_GetValueCaps and other functions in hid.dll are not present

### ISSUE THREAD

**Issue by jnm2** [AArnott/pinvoke#530]
Examples:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/nf-hidpi-hidp_getdata
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/nf-hidpi-hidp_getusagevaluearray
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidpi/nf-hidpi-hidp_getvaluecaps
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/hidsdi/nf-hidsdi-hidd_getindexedstring

**Comment by shaise** [comment]
+1
it looks like it was implemented in old versions, as i saw it used in code samples
