### ISSUE TITLE
User32 raw input API is not present

### ISSUE THREAD

**Issue by jnm2** [AArnott/pinvoke#531]
E.g.:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerrawinputdevices

**Comment by Lakritzator** [comment]
Maybe I can have a go add this, but not sure when I have the time.

Anyway, you might want to look at the code here if you need some examples:
https://github.com/dapplo/Dapplo.Windows/blob/master/src/Dapplo.Windows.Input/RawInputApi.cs

**Comment by AArnott** [comment]
Thanks for volunteering, @Lakritzator. 

I would encourage anyone thinking about contributing to the repo to not do anything about it this week in particular. I am not at liberty to say why just yet, but wait till this weekend and reevaluate.
