### ISSUE TITLE
User32 LastInputInfo is missing?

### ISSUE THREAD

**Issue by dhunt84971** [AArnott/pinvoke#537]
I haven't been able to find this function, but it's possible I am not looking in the right place or it has not been implemented yet.

If not implemented I would like to submit the request to have it added.

I am using VSCode with the NuGet Package Manager and the PInvoke.User32 package installed under Window 10.

**Comment by AArnott** [comment]
Per our README, we don't have 100% coverage for every library, so you likely found a method that simply hasn't been added yet. You're welcome to send a PR to add it. Please review our README and CONTRIBUTING docs carefully before doing so.

**Comment by AArnott** [comment]
Closed by #542
