### ISSUE TITLE
where's Sleep function?

### ISSUE THREAD

**Issue by Haceau-Zoac** [AArnott/pinvoke#547]

**Comment by jrimig** [comment]
System.Threading.Thread.Sleep()?
https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.sleep?view=net-5.0

**Comment by Haceau-Zoac** [comment]
> System.Threading.Thread.Sleep()?
> https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.sleep?view=net-5.0

Thanks!
