### ISSUE TITLE
How does this project and win32metadata interact

### ISSUE THREAD

**Issue by MikeAtETI** [AArnott/pinvoke#564]
Having read the blog at https://blogs.windows.com/windowsdeveloper/2021/01/20/making-win32-apis-more-accessible-to-more-languages/ - which links to a project which isn't public yet but seems to be "next generation" of this - are the output consistent (so we can just change nugets)?

**Comment by AArnott** [comment]
Great question. And ya, that blog post went live before we intended, thus the broken links. Thanks for letting us know so we can get that worked out.

The output is *not* the same. The C# projection is heavily inspired by this repo's patterns and lessons learned, but exact equivalence was not a goal.
We anticipate most folks moving from consuming nuget packages produced by this repo to the C# projection over at https://github.com/microsoft/CsWin32.

If any folks cannot do that, we'd like to learn why.

If interest in *this* project remains, we will likely migrate to a model where we are just a pre-built projection of the CsWin32 project.

**Comment by AArnott** [comment]
See also #565 for more on this.
