### ISSUE TITLE
FormatMessage returns chinese/japan error message.

### ISSUE THREAD

**Issue by joffarex** [AArnott/pinvoke#578]
So I had been trying to get error messages, but whenever I try it, it always returns chinese/japan or some similar symbols.

Example 1:
```csharp
FormatMessage(FormatMessageFlags.FORMAT_MESSAGE_ALLOCATE_BUFFER | FormatMessageFlags.FORMAT_MESSAGE_FROM_SYSTEM |
                FormatMessageFlags.FORMAT_MESSAGE_IGNORE_INSERTS, IntPtr.Zero, hResult,
                0x0409, null, 256)
```
Returns: 㓰�ɖ

Same example ran with 
```csharp
MAKELANGID(LANGID.PrimaryLanguage.LANG_NEUTRAL, LANGID.SubLanguage.SUBLANG_NEUTRAL).Data
```
Returns: ᕰǻ

I have also tried to use StringBuilder but without any result
```csharp
 FormatMessage(FormatMessageFlags.FORMAT_MESSAGE_ALLOCATE_BUFFER | FormatMessageFlags.FORMAT_MESSAGE_FROM_SYSTEM |
            FormatMessageFlags.FORMAT_MESSAGE_IGNORE_INSERTS, IntPtr.Zero, hResult,
            0x0409, msgBuffer, 0,
            null);
```
Returns: 簠đ

And with MAKELANGID call as previous example
Returns: ௐ疋ȉ

I could be doing something wrong as well, I am not really fluent with Win32, but I have to point out that I have tried this piece of code, and it worked and gave me error messages in English, so I am kind of thinking that this lib's implementation could be bugged:
```csharp
using System;
using System.Runtime.InteropServices;
using static PInvoke.Kernel32;

public static class Test
{
    [DllImport("kernel32.dll", SetLastError = true)]
    static extern int FormatMessage(FormatMessageFlags dwFlags, IntPtr lpSource, uint dwMessageId, uint dwLanguageId,
        ref IntPtr lpBuffer, uint nSize, IntPtr Arguments);

    [Flags]
    private enum FormatMessageFlags : uint
    {
        FORMAT_MESSAGE_ALLOCATE_BUFFER = 0x00000100,
        FORMAT_MESSAGE_IGNORE_INSERTS = 0x00000200,
        FORMAT_MESSAGE_FROM_SYSTEM = 0x00001000,
    }

    public static string GetSystemMessage(int errorCode)
    {
        IntPtr msgBuffer = IntPtr.Zero;

        var langID = MAKELANGID(LANGID.PrimaryLanguage.LANG_NEUTRAL, LANGID.SubLanguage.SUBLANG_NEUTRAL);

        int msgLength = FormatMessage(
            FormatMessageFlags.FORMAT_MESSAGE_ALLOCATE_BUFFER | FormatMessageFlags.FORMAT_MESSAGE_FROM_SYSTEM |
            FormatMessageFlags.FORMAT_MESSAGE_IGNORE_INSERTS,
            IntPtr.Zero,
            (uint) errorCode,
            langID.Data,
            ref msgBuffer,
            0,
            IntPtr.Zero);

        string error = Marshal.PtrToStringAnsi(msgBuffer);

        return error;
    }
}
```

I am using:
------------
.NET version:    5.0.202
Processor:	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM:	16.0 GB
Edition:	        Windows 10 Pro
Version:	        20H2
OS build:	        19042.985
Language: English-US

**Comment by joffarex** [comment]
Just to add, I have been playing around with my own interop, and I think I am getting to the core of the issue:

The function works with this attribute
```csharp
    [DllImport("api-ms-win-core-localization-l1-2-0.dll", SetLastError = true)]
```

But whenever I add any attribute params from this library
```csharp
CharSet = CharSet.Unicode, EntryPoint = "FormatMessageW",
```
It returns only first symbol of the error message.

**Update**: But it is not the core of the issue, as I tried to use StringBuilder instead of IntPtr inside my own implementation and it started returning weird symbols again. it never returned correct value with or without previously mentioned attribute params, when the lpBuffer was a StringBuilder.

**Comment by AArnott** [comment]
I think the problem stems from your calling `Marshal.PtrToStringAnsi(msgBuffer);` when the buffer was initialized with a unicode string rather than an ansi one.

**Comment by joffarex** [comment]
Hm could be the case for my implementation, I'll see it tomorrow. 

But what would be the issue with this library's implementation? 🤔

**Comment by AArnott** [comment]
I don't know that there is an issue here. If you use this library and then interpret the data as unicode, does it work?
