### ISSUE TITLE
Request: Control Code constants for DeviceIoControl()

### ISSUE THREAD

**Issue by BinToss** [AArnott/pinvoke#596]
e.g. FSCTL_SET_COMPRESSION

**Comment by AArnott** [comment]
Have you tried CsWin32? It includes this constant (if you fix the typo: FSCTL_SET_COMPRESSION)

**Comment by BinToss** [comment]
Yes, but it only works in Visual Studio right now.
VSCode's OmniSharp extension doesn't support CsWin32's code generation at the moment.
It compiles, but the editor doesn't recognize any of the CsWin32 symbols.

**Comment by AArnott** [comment]
Ah, yes. That makes sense.
I haven't had any time lately to spend on adding APIs to this repo, nor yet to finish replacing the hand-coded APIs in the repo with the result of CsWin32 code generation. Until then, if you'd like to send a PR to add these constants, I typically can find time to review and merge those. You could even use CsWin32 in VS to help you get the C# code to insert into this repo. The code placement conventions are a little different in this repo so you'd need to account for that.

**Comment by BinToss** [comment]
I'd started to add a bunch of constants to a class, so I'll clean that up for a PR.
I might have time next weekend for this.
