### ISSUE TITLE
Request: Better exception handling or documentation for CreateFile

### ISSUE THREAD

**Issue by BinToss** [AArnott/pinvoke#598]
The following code block results in an exception thrown by mscorlib (.NET Framework 4.6.2) with little explanation of its cause.
```cs
var directoryInfo = new DirectoryInfo("D:/SymbolCache");
Kernel32.SECURITY_ATTRIBUTES? sa = null;
Kernel32.SafeObjectHandle hDirectory = Kernel32.CreateFile(
    filename: directoryInfo.FullName,
    access: Kernel32.ACCESS_MASK.GenericRight.GENERIC_READ | Kernel32.ACCESS_MASK.GenericRight.GENERIC_WRITE,
    share: Kernel32.FileShare.None,
    securityAttributes: sa,
    creationDisposition: Kernel32.CreationDisposition.OPEN_EXISTING,
    flagsAndAttributes: Kernel32.CreateFileFlags.FILE_FLAG_BACKUP_SEMANTICS,
    templateFile: null
);
```
```
Parameter name: SafeHandle cannot be null.
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at PInvoke.Kernel32.CreateFile(Char* filename, ACCESS_MASK access, FileShare share, SECURITY_ATTRIBUTES* securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
   at PInvoke.Kernel32.CreateFile(String filename, ACCESS_MASK access, FileShare share, Nullable`1 securityAttributes, CreationDisposition creationDisposition, CreateFileFlags flagsAndAttributes, SafeObjectHandle templateFile)
```
Which parameter caused the NullArgumentException? templateFile? filename? securityAttributes?
Is it an issue that did not originate from my code or even PInvoke.Kernel32 for that matter?

**Comment by BinToss** [comment]
In hindsight, this may be a request for the Windows API itself, rather than a wrapper.
Still, If anyone knows how this SafeHandle became null, I'd appreciate an explanation and some suggestions.

Edit: I may need to double-check if SeBackupPrivilege was set properly.

**Comment by AArnott** [comment]
You passed in a null SafeHandle yourself: `templateFile: null`.

.NET interop cannot handle a null `SafeHandle`. You must create a `SafeHandle` with an invalid/null native handle and pass that in explicitly.

**Comment by BinToss** [comment]
Ah, thank you! The documentation said the parameter could be null, but I suppose that isn't the case.
