### ISSUE TITLE
Finalize naming conventions in guidance doc and code

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#60]
To ship a stable NuGet package, our API must be stable. That means we need to agree on a fully-spec'd proposal for naming conventions and make sure they are consistently applied in the actual code.

**Comment by vbfox** [comment]
I did a fast pass in the code, the things that seem to need renaming are :
- [x] `CreateFileFlags` members
- [x] `CreationDisposition` members
- [x] `FileAccess` members 
- [x] `FileShare` members
- [x] `SecurityImpersonationLevel` (The native version is named `SECURITY_IMPERSONATION_LEVEL`)
- [x] `FileAttribute` members
- [x] `FindFirstFileExFlags` members
- [x] `FormatMessageFlags` members
- [x] `WindowShowStyle` members
- [x] `BCrypt+PropertyNames` members

**Comment by AArnott** [comment]
Thanks, @vbfox.
I've never seen a checklist in markdown before. Cool.

**Comment by vbfox** [comment]
It's a github specific feature, if you include it in the issue text it'll show when the issue is referenced with how many of the points are checked.

Also you can check the points by clicking on the checkbox and it update the text of the comment/issue to change [ ] to [x]

**Comment by vbfox** [comment]
I'll attempt a rename of the points I listed in my comment and will report on what remains if I didn't completely finish.

**Comment by AArnott** [comment]
Is there anything else to fix for this in the code, @vbfox and @jmelosegui ? Or should we close this?

**Comment by vbfox** [comment]
I didn't see anything more about naming itself, but the `uint` -> `int` conversion remains I think (Don't know if it should be in this issue or another one)

**Comment by AArnott** [comment]
Opened #88 to track
