### ISSUE TITLE
Support for .NET 6 to include in Maui?

### ISSUE THREAD

**Issue by logikonline** [AArnott/pinvoke#609]
Can you please offer a .NET 6 version?

**Comment by AArnott** [comment]
What are you hoping it will offer that the existing netstandard2.0 TFM (which applies to net6.0) doesn't cover? How does Maui related to this request?

**Comment by logikonline** [comment]
I was unaware it applies to .net6, I had been conditioned to look for .net6 in the dependencies list.  Thx.
