### ISSUE TITLE
`User32.EnumChildWindows` has wrong typed argument

### ISSUE THREAD

**Issue by ijklam** [AArnott/pinvoke#611]
The type of argument `lpEnumFunc` should be `User32.WNDENUMPROC`, but currently is `nativeint` (`IntPtr`)

![image](https://user-images.githubusercontent.com/43789618/189122103-78e2d0dc-6ca9-4367-8114-10db0a014fb1.png)

**Comment by AArnott** [comment]
Consider using CsWin32 instead, which already has this right.
