### ISSUE TITLE
Kernel32.QueryFullProcessImageName broken on Windows 7

### ISSUE THREAD

**Issue by josephmoresena** [AArnott/pinvoke#623]
When trying to invoke Kernel32.QueryFullProcessImageName on Windows 7, the call fails due to missing api-ms-win-core-psapi-l1-1-0.dll.

**Comment by AArnott** [comment]
Can you try CsWin32 instead?

**Comment by AArnott** [comment]
Also, Windows 7 hasn't been under Microsoft support for [a long time](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962).
