### ISSUE TITLE
Type of DLGTEMPLATE

### ISSUE THREAD

**Issue by lanyizi** [AArnott/pinvoke#629]
https://github.com/dotnet/pinvoke/blob/92349c675931c0057e9749e1f3488f6fe2d8692e/src/User32/User32%2BDLGTEMPLATE.cs#L50
Are we sure that here are `byte` instead of `short`?
https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-dlgtemplate

**Comment by AArnott** [comment]
Thanks for this report. 
A fix is in progress. But in the meantime, consider using CsWin32 which is less likely to have bugs like this.
