### ISSUE TITLE
User32.SetLayeredWindowAttributes missing

### ISSUE THREAD

**Issue by kyleshrader** [AArnott/pinvoke#631]
This is an API request for user32.dll's SetLayeredWindowAttributes:

```cpp
BOOL SetLayeredWindowAttributes(
  [in] HWND     hwnd,
  [in] COLORREF crKey,
  [in] BYTE     bAlpha,
  [in] DWORD    dwFlags
);
```

See: https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setlayeredwindowattributes

**Comment by AArnott** [comment]
Can you [use CsWin32](565) instead?

**Comment by kyleshrader** [comment]
I will certainly give it a try. Thanks
