### ISSUE TITLE
Missing user32 DeleteMenu

### ISSUE THREAD

**Issue by SAPTeamDEV** [AArnott/pinvoke#640]
Hi
I want to delete close button of my console window but i have seen that this library is not have an overload for deletemenu

**Comment by AArnott** [comment]
Can you use CsWin32? It can produce `DeleteMenu`, along with virtually all other Win32 APIs.

**Comment by SAPTeamDEV** [comment]
I have solved the problem temporarily by importing direct win32 api, but if this api added to PInvoke it will be greate.

PS: English is not my native language

**Comment by AArnott** [comment]
This repo isn't getting much work anymore because https://github.com/microsoft/CsWin32 has replaced it. I suggest you try that out and see if it can replace your need for this repo.

**Comment by SAPTeamDEV** [comment]
I have installed this library yesterday but I could not work with it.  I have read all the instructions on GitHub

**Comment by AArnott** [comment]
Thanks for reporting back. Sorry it didn't work for you. If you can, create a discussion (not an issue) on the CsWin32 repo and share exactly what you tried and where it failed. I maintain that repo too, and will be happy to support you there.
