### ISSUE TITLE
Missing user32 RegisterHotKey

### ISSUE THREAD

**Issue by popyoung** [AArnott/pinvoke#642]
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey

**Comment by AArnott** [comment]
Can you use CsWin32 as described in https://github.com/dotnet/pinvoke/issues/565 for this API? This repo is deprecated.

**Comment by popyoung** [comment]
I noticed that after posting that. Thanks for your work.
