### ISSUE TITLE
How do I find Windows headers?

### ISSUE THREAD

**Issue by ffMathy** [AArnott/pinvoke#66]
I installed the Windows 10 standalone SDK, and I can't find my header files for PInvoke based operations. Do you know where they are?

**Comment by AArnott** [comment]
The way I find them is create a C++ project in Visual Studio, add an `#include <windows>` line (or whatever the file is per the docs) and then hit Go To Definition (or Ctrl+Shift+G) on that line so VS will open the file.

**Comment by vbfox** [comment]
On my PC they are all under `C:\Program Files (x86)\Windows Kits\10\` my normal routing is to go there with gVim and grep the `.h` files for the api names/constants I want.
