### ISSUE TITLE
Win32Exception.GetErrorMessage throws DllNotFoundException on WPA81

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#77]
WinRT (on PC) is fine, but on wpa81 in particular, Kernel32's `FormatMessage` method seems to be unreachable, as shown in the emulator screenshot below. 
I've sent an email to a Microsoft DL asking for more info since the [MSDN doc for FormatMessage](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679351%28v=vs.85%29.aspx) suggests this should work.

![missingformatmessage](https://cloud.githubusercontent.com/assets/3548/11377873/2f64486c-929d-11e5-9a95-d94c7db8601f.png)

**Comment by vbfox** [comment]
This intrigued me so I did a bit of search and [what people are saying](https://stackoverflow.com/questions/28464217/how-to-p-invoke-into-kernel32-dll-on-winrt-8-1) is that on this platform the old style dlls might not exist to redirect to the [API Sets](https://msdn.microsoft.com/en-us/library/windows/desktop/hh802935%28v=vs.85%29.aspx). So the P/Invoke need to be to `api-ms-win-core-localization-l1-2-1.dll` (Didn't test)

**Comment by AArnott** [comment]
Thanks, @vbfox. I'll draft up a PR to propose how we deal with this.

**Comment by AArnott** [comment]
How rampant do you think this problem is? Do all our P/Invoke methods need to support API sets or is it something that only some kernel32 methods need? Is that an implementation detail of Windows where it's unsafe to use Kernel32.dll at all for modern platforms?

**Comment by AArnott** [comment]
Given that some OS versions require the old DLL name and some require the new one, we need to make one high-level design decision early as to whether we accommodate these differences at runtime or compile time. 

**Compile time**
We compile twice, using `#if` to switch between `kernel32` and the api set name.
This minimizes the DLL size and runtime overhead. We can use NuGet packaging lib\TxM folders to get folks to use the right PInvoke DLL given their target platform. If the TxM options fit well enough, this is a viable option. But it means 2-3X the number of projects in our solution as each project has to compile twice, and we'd use Shared Projects to share code between them. 
We may also need to do some clever .NuProj authoring so that the DLLs get laid out in the nupkg appropriately.

**Runtime**
We double the number of P/Invoke methods and make them all private -- one set point at kernel32 and the other set uses the api set name. We then add yet _another_ set of methods (we're now at triple the number of methods we have today) to make a runtime check and call into the appropriate P/Invoke method based on the OS version.

I'm leaning toward the compile-time option.

**Comment by AArnott** [comment]
The compile-time option looks more appealing now that I've prepared changes for Kernel32.dll. It doesn't require doubling projects. It seems to align nicely with the existing portable/desktop split.

**Comment by vbfox** [comment]
Compilation time seem better and your solution seem clean.

As long as all future platforms support API sets (and it seem to be the direction) I can't think of any problem.

We might want to update the contributing docs on how the correct set should be found and used.

Does it affect only Kernel32 ?

**Comment by jmelosegui** [comment]
@AArnott I like your solution too. My only concern would be how many #if branches we'll end up having and how easy will be to maintain them.

The following is an example of the FormatMessage function located in 3 differen dlls.

| Function Name | Pre Api sets | Windows 10, Windows 8.1 and Windows Server 2012 R2 | Windows 8 and Windows Server 2012 |
| --- | --- | --- | --- |
| FormatMessage | kernel32.dll | api-ms-win-core-localization-l1-2-1.dll | api-ms-win-core-localization-l1-2-0.dll |

as you can see we have at least 3 different dll names.

@vbfox No, it seems to apply to more apis. If you go [here](https://msdn.microsoft.com/en-us/library/windows/desktop/hh802935%28v=vs.85%29.aspx) and search for `EnumServicesStatusEx` you will find that function under api-ms-win-service-core-l1-1-1.dll.

**Comment by AArnott** [comment]
@jmelosegui Yikes. I thought the point of API sets was that the method can always be found at the same place regardless of implementation, and yet the method is in different API sets based on Windows version?  But I wonder if the 1-2-1 vs. 1-2.0 is just a version # and we can use the smallest version even on the newest platform? I'll test that out.
So long as that is the case, There is just one `#if` at the top of each file so while it's tedious, IMO it's manageable.

**Comment by AArnott** [comment]
I've confirmed that we can use the lowest version number in the API Set that it ever appears in and it still works on newer OSs. So I think we're good.
