### ISSUE TITLE
API review of NullableGuid and NullableUInt32

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#91]

**Comment by AArnott** [comment]
All the explicit casts make it difficult to work with, particularly for folks who want to work with `int` instead of `uint`. I have a git stash where I tried to change all `NullableUInt32` to `out uint` parameters and code got noticeably simpler, even though a couple places needed to start defining locals where `null` could be passed before. However it caused a test failure because in one case it's _necessary_ to pass `null` into the parameter which of course isn't possible with `ref` or `out` struct parameters.

Another approach is to have the p/invoke method take `uint*` or `int*` instead. That way, no unnatural casts or object allocations are required and both null and structs will be allowed. However the caller would have use `unsafe` (which isn't _too_ bad) and (worst of all IMO) direct values wouldn't be allowed and would instead have to be packed into a local variable first. That's not an issue for `out` parameters but for `[In] LPDWORD` parameters so that a number or NULL can be passed in, it's particularly problematic. That last one is the same scenario where `NullableUInt` shines though, and IMO could even more if it used implicit cast operators instead of explicit ones. 

@vbfox can you tell me why you chose to use explicit cast operators instead of implicit ones?
Also, how do you feel about adding `int` cast operators a well? Or should we just change it all from uint-based to int-based?

**Comment by vbfox** [comment]
> can you tell me why you chose to use explicit cast operators instead of implicit ones?

It was because at start I feared that some cases wouldn't work cleanly / be confusing.
But I did some tests since then an having only implicit operators to/from `Nullable<uint>` is a lot more readable and the case of doing . `NullableGuid` should get the same treatment IMHO.

The case that I feared is the double conversion like in :

``` csharp
void Main()
{
    uint x = 0;
    Foo(x);
    Foo(null);
    Foo(42);
}

public NullableUInt32 Foo(NullableUInt32 nui)
{
    return nui;
}
```

But the compiler is smart enough to allow a double conversion (the nullable one + the user defined one) so it works.

> Also, how do you feel about adding int cast operators a well? Or should we just change it all from uint-based to int-based?

We already decided that we would use int everywhere so I don't see any reason to keep it `uint` based. It should be migrated to a `NullableInt32` if we keep it.

**Comment by AArnott** [comment]
Sounds good so far. As for whether we keep it or not, I'm leaning toward keeping it unless we can find a combination of pointers and overloads that ensure the experience is complete and reasonably good everywhere. So I'm working a bit on #76 now (converting IntPtr methods to pointers) to see what impact it has overall.

**Comment by vbfox** [comment]
Regarding pointers, the experience isn't so bad for users of language with unsafe structure. It's even easier to understand for users coming from a C background.
But from a language that doesn't have them we would need the the `out` / `ref` version. And the experience when the `IntPtr` version is needed would be pretty bad (Depends how much we want the experience to be good from no-unsafe languages)

---

Also another thing to consider in the API of `NullableUInt32` is that we might want conversion methods in addition to operators if we target CLS compliance (If I remember well the CLS things allowed don't include operators)

**Comment by AArnott** [comment]
I don't think CLS compliance is a goal. We're doing very low-level stuff here. I'm not against it, and perhaps can be persuaded as to it being a goal. But `uint` for example itself isn't CLS compliant IIRC.

**Comment by AArnott** [comment]
I was just looking at some code that uses NullableInt32. I notice that it isn't as obvious as a `ref` or `out` parameter would be that the value is initialized by the method being called.

**Comment by AArnott** [comment]
Related to #137, I propose that the enhancement to the code generator include recognizing the `[In]` attribute next to a `struct*` so that it knows the value only goes _in_ and not _out_. Then instead of generating a `ref struct` overload, the generated helper method will take `struct?` allowing it to be conveniently optional, without the need for `NullableGuid` or `NullableUInt32`.
