### ISSUE TITLE
Codegen IntPtr-accepting overloads of methods with native pointers

### ISSUE THREAD

**Issue by vbfox** [AArnott/pinvoke#95]
#76 should be done first. See that issue for the rationale.

For now we'll use only a few pointers when deemed necessary and hand-craft `IntPtr` alternatives, but what would really be interesting is to only have to write the pointer versions and have the `IntPtr` overload auto-generated.

Code generation will also be needed for #55 so both issues would need the same infrastructure.

**Comment by AArnott** [comment]
> Code generation will also be needed for #55 so both issues would need the same infrastructure.

Just a note: #55 might be rather different from this one at least in how it's wired up. #55 may produce a separate assembly and that assembly might be in its own NuGet package as well, whereas the code gen for IntPtr would definitely produce code for the same assembly.

**Comment by AArnott** [comment]
I'm going to do some experimentation with this using the basis for build-time code generation I developed here: https://github.com/AArnott/ImmutableObjectGraph/tree/master/src/ImmutableObjectGraph.CodeGeneration

**Comment by AArnott** [comment]
OK, I've finished pulling out the basis of build-time code generation into this new project:
https://github.com/AArnott/CodeGeneration.Roslyn

I'll work on applying it to this project next.
